version: 2.1

orbs:
  snyk: snyk/snyk@1.1.1

jobs:
  build:
    working_directory: ~/oddsite
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: oddsite-{{ checksum ".pnp.cjs" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable --immutable-cache
      - persist_to_workspace:
          root: .
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz
      - save_cache:
          key: oddsite-{{ checksum ".pnp.cjs" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
            - ./.yarn/install-state.gz

  lint:
    working_directory: ~/oddsite
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test:
    working_directory: ~/oddsite
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test JS
          command: yarn dlx -p jest-junit jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: './coverage'
      - store_artifacts:
          path: coverage
          destination: js-test-reports
      - store_test_results:
          path: coverage

  snyk:
    working_directory: ~/oddsite
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - snyk/scan:
          additional-arguments: --dev
          fail-on-issues: false
          monitor-on-build: true
          organization: oddbird

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - snyk:
          requires:
            - build
