version: 2.1
jobs:
  build:
    working_directory: ~/oddleventy
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - restore_cache:
          key: oddleventy-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable --immutable-cache
      - save_cache:
          key: oddleventy-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/unplugged
            - ./.yarn/build-state.yml
      - run:
          name: Lint JS & Sass
          command: yarn lint
