url: https://oddbird.net
title: OddBird
description: |
  Scalable, accessible, and performant web applications
  with a human-centered design.
email: birds@oddbird.net
images: /assets/images/
feed: /feed.xml
styles:
  - screen.css
facebook_id: 1820980378150914
social:
  email: birds
  twitter: oddbird
nav:
  - url: /work/
  - url: /services/
  - url: /birds/
  - url: /blog/
  - url: /contact/
